### ISSUE TITLE
rotating/scaling/zooming a single shape/interactive object in a view among many objects

### ISSUE THREAD

**Issue by 007atanu** [eryar/occQt#12]
I have created a application where there is a viewer and a view and a context. i have several AIS_Interectiveobjects/AIS_Shape s in the view .If i rotate the view all my objects in the view is rotating.I want to rotate/scale/zoom the selected objects among them may be one at a time. what is the best way to do? 

a small example will do great.

**Comment by eryar** [comment]
Hi @007atanu 

When you rotate/pan/zoom the view, all the AIS_Shape in the view will be rotate/pan/zoom.

I think you need a model dragger, like I mention in there:
https://github.com/eryar/occQt/issues/5

Best Regards,
Shing Liu

**Comment by eryar** [comment]
OpenCASCADE7.1.0 introduce AIS_Minpulator to do this, you can have a try.
