### ISSUE TITLE
#error qmetatype.h must be included before any header file that defines Bool

### ISSUE THREAD

**Issue by mahaidong** [eryar/occQt#13]
我在ubuntu环境下编译的时候有这个错误， 然后我把所有到qt头文件都方在文件最开始的地方，就可以通过了

我参考了这里的方法：  https://github.com/zballina/lxqt-config-randr/issues/7

**Comment by lpaone** [comment]
Hello, me too. I resolved this changing the includes order

**Comment by eryar** [comment]
Good!
我编译的时候没遇到，可能是Windows里面。

**Comment by mahaidong** [comment]
对， 只在ubuntu上出现， 好像在mac上也没有。
