### ISSUE TITLE
Compilation on ubuntu

### ISSUE THREAD

**Issue by gregorito** [eryar/occQt#2]
Hey,
I tried to compile your project on ubuntu 14.04 after installing all the required file detailed in the readmefile. But im getting some error which are from the oce lib i think. Any idea how to make it work ? here is the output from the compiler.
Thanks in advance, your sample looks awesome! 

18:05:35: Running steps for project occQt...
18:05:35: Configuration unchanged, skipping qmake step.
18:05:35: Starting: "/usr/bin/make" 
g++ -c -m64 -pipe -g -Wall -W -D_REENTRANT -fPIE -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../occQt -I/usr/include/oce -I/usr/include/qt5 -I/usr/include/qt5/QtOpenGL -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I. -I. -I. -o occQt.o ../occQt/occQt.cpp
In file included from /usr/include/oce/Graphic3d_Structure.hxx:14:0,
                 from /usr/include/oce/Prs3d_Presentation.hxx:13,
                 from /usr/include/oce/PrsMgr_ListOfPresentations.hxx:20,
                 from /usr/include/oce/PrsMgr_PresentationManager.hxx:15,
                 from /usr/include/oce/PrsMgr_PresentationManager3d.hxx:9,
                 from /usr/include/oce/AIS_InteractiveContext.hxx:15,
                 from ../occQt/occQt.h:18,
                 from ../occQt/occQt.cpp:12:
/usr/include/oce/TCollection_Sequence.lxx: In copy constructor 'TColStd_SequenceOfAddress::TColStd_SequenceOfAddress(const TColStd_SequenceOfAddress&)':
/usr/include/oce/TColStd_SequenceOfAddress.hxx:109:30: warning: base class 'class TCollection_BaseSequence' should be explicitly initialized in the copy constructor [-Wextra]
 #define TCollection_Sequence TColStd_SequenceOfAddress
                              ^
/usr/include/oce/TCollection_Sequence.lxx:31:8: note: in expansion of macro 'TCollection_Sequence'
 inline TCollection_Sequence::TCollection_Sequence(const TCollection_Sequence& theOther)
        ^
In file included from /usr/include/oce/AIS_InteractiveContext.hxx:27:0,
                 from ../occQt/occQt.h:18,
                 from ../occQt/occQt.cpp:12:
/usr/include/oce/TCollection_Sequence.lxx: In copy constructor 'AIS_SequenceOfInteractive::AIS_SequenceOfInteractive(const AIS_SequenceOfInteractive&)':
/usr/include/oce/AIS_SequenceOfInteractive.hxx:110:30: warning: base class 'class TCollection_BaseSequence' should be explicitly initialized in the copy constructor [-Wextra]
 #define TCollection_Sequence AIS_SequenceOfInteractive
                              ^
/usr/include/oce/TCollection_Sequence.lxx:31:8: note: in expansion of macro 'TCollection_Sequence'
 inline TCollection_Sequence::TCollection_Sequence(const TCollection_Sequence& theOther)
        ^
In file included from /usr/include/oce/V3d_Viewer.hxx:51:0,
                 from /usr/include/oce/V3d_View.hxx:36,
                 from ../occQt/occQt.h:19,
                 from ../occQt/occQt.cpp:12:
/usr/include/oce/Graphic3d_ZLayerSettings.hxx: At global scope:
/usr/include/oce/Graphic3d_ZLayerSettings.hxx:38:86: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const Standard_Boolean IsSettingEnabled (const Graphic3d_ZLayerSetting theSetting) const
                                                                                      ^
In file included from ../occQt/occView.h:16:0,
                 from ../occQt/occQt.cpp:13:
/usr/include/oce/OpenGl_GraphicDriver.hxx:377:50: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   const Standard_Size GetNextPrimitiveArrayUID() const { return myUIDGenerator.Increment(); }
                                                  ^
In file included from /usr/include/X11/Xlib.h:44:0,
                 from /usr/include/oce/InterfaceGraphic.hxx:30,
                 from /usr/include/oce/OpenGl_GlFunctions.hxx:138,
                 from /usr/include/oce/OpenGl_GlCore11Fwd.hxx:19,
                 from /usr/include/oce/OpenGl_GlCore11.hxx:19,
                 from /usr/include/oce/OpenGl_Context.hxx:39,
                 from /usr/include/oce/OpenGl_GraphicDriver.hxx:21,
                 from ../occQt/occView.h:16,
                 from ../occQt/occQt.cpp:13:
/usr/include/oce/math_Vector.hxx:273:31: error: expected unqualified-id before numeric constant
   Standard_EXPORT math_Vector Opposite();
                               ^
In file included from /usr/include/oce/ChFi3d_Builder.hxx:33:0,
                 from /usr/include/oce/ChFi3d_FilBuilder.hxx:14,
                 from /usr/include/oce/BRepFilletAPI_MakeFillet.hxx:13,
                 from ../occQt/occQt.cpp:43:
/usr/include/oce/math_Vector.hxx: In member function 'math_Vector math_Vector::operator-()':
/usr/include/oce/math_Vector.hxx:277:21: error: expression cannot be used as a function
     return Opposite();
                     ^
In file included from /usr/include/oce/ChFi2d_Builder.hxx:15:0,
                 from /usr/include/oce/BRepFilletAPI_MakeFillet2d.hxx:13,
                 from ../occQt/occQt.cpp:44:
/usr/include/oce/TCollection_Sequence.lxx: In copy constructor 'TopTools_SequenceOfShape::TopTools_SequenceOfShape(const TopTools_SequenceOfShape&)':
/usr/include/oce/TopTools_SequenceOfShape.hxx:109:30: warning: base class 'class TCollection_BaseSequence' should be explicitly initialized in the copy constructor [-Wextra]
 #define TCollection_Sequence TopTools_SequenceOfShape
                              ^
/usr/include/oce/TCollection_Sequence.lxx:31:8: note: in expansion of macro 'TCollection_Sequence'
 inline TCollection_Sequence::TCollection_Sequence(const TCollection_Sequence& theOther)
        ^
In file included from /usr/include/oce/SelectMgr_SelectableObject.hxx:13:0,
                 from /usr/include/oce/AIS_InteractiveObject.hxx:24,
                 from /usr/include/oce/AIS_Shape.hxx:17,
                 from ../occQt/occQt.cpp:55:
/usr/include/oce/TCollection_Sequence.lxx: In copy constructor 'SelectMgr_SequenceOfSelection::SelectMgr_SequenceOfSelection(const SelectMgr_SequenceOfSelection&)':
/usr/include/oce/SelectMgr_SequenceOfSelection.hxx:110:30: warning: base class 'class TCollection_BaseSequence' should be explicitly initialized in the copy constructor [-Wextra]
 #define TCollection_Sequence SelectMgr_SequenceOfSelection
                              ^
/usr/include/oce/TCollection_Sequence.lxx:31:8: note: in expansion of macro 'TCollection_Sequence'
 inline TCollection_Sequence::TCollection_Sequence(const TCollection_Sequence& theOther)
        ^
In file included from /usr/include/oce/PrsMgr_PresentableObject.hxx:13:0,
                 from /usr/include/oce/SelectMgr_SelectableObject.hxx:17,
                 from /usr/include/oce/AIS_InteractiveObject.hxx:24,
                 from /usr/include/oce/AIS_Shape.hxx:17,
                 from ../occQt/occQt.cpp:55:
/usr/include/oce/TCollection_Sequence.lxx: In copy constructor 'PrsMgr_Presentations::PrsMgr_Presentations(const PrsMgr_Presentations&)':
/usr/include/oce/PrsMgr_Presentations.hxx:109:30: warning: base class 'class TCollection_BaseSequence' should be explicitly initialized in the copy constructor [-Wextra]
 #define TCollection_Sequence PrsMgr_Presentations
                              ^
/usr/include/oce/TCollection_Sequence.lxx:31:8: note: in expansion of macro 'TCollection_Sequence'
 inline TCollection_Sequence::TCollection_Sequence(const TCollection_Sequence& theOther)
        ^
In file included from /usr/include/oce/SelectMgr_SelectableObject.hxx:17:0,
                 from /usr/include/oce/AIS_InteractiveObject.hxx:24,
                 from /usr/include/oce/AIS_Shape.hxx:17,
                 from ../occQt/occQt.cpp:55:
/usr/include/oce/PrsMgr_PresentableObject.hxx: At global scope:
/usr/include/oce/PrsMgr_PresentableObject.hxx:178:57: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   Standard_EXPORT  const  Standard_Boolean IsMutable()  const;
                                                         ^
/usr/include/oce/PrsMgr_PresentableObject.hxx:190:67: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   Standard_EXPORT  const  Standard_Boolean HasOwnPresentations()  const;
                                                                   ^
/usr/include/oce/PrsMgr_PresentableObject.hxx:193:69: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
   Standard_EXPORT  const  PrsMgr_PresentableObjectPointer Parent()  const;
                                                                     ^
In file included from /usr/include/oce/PrsMgr_PresentableObject.hxx:290:0,
                 from /usr/include/oce/SelectMgr_SelectableObject.hxx:17,
                 from /usr/include/oce/AIS_InteractiveObject.hxx:24,
                 from /usr/include/oce/AIS_Shape.hxx:17,
                 from ../occQt/occQt.cpp:55:
/usr/include/oce/PrsMgr_PresentableObject.lxx:36:79: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
 inline const Standard_Boolean PrsMgr_PresentableObject::HasOwnPresentations() const
                                                                               ^
/usr/include/oce/PrsMgr_PresentableObject.lxx:41:81: warning: type qualifiers ignored on function return type [-Wignored-qualifiers]
 inline const PrsMgr_PresentableObjectPointer PrsMgr_PresentableObject::Parent() const
                                                                                 ^
../occQt/occQt.cpp: In member function 'void occQt::makeBox()':
../occQt/occQt.cpp:286:62: error: conversion from 'BRepPrimAPI_MakeBox' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoBox = BRepPrimAPI_MakeBox(3.0, 4.0, 5.0);
                                                              ^
../occQt/occQt.cpp:286:62: note: candidates are:
In file included from ../occQt/occQt.cpp:36:0:
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:76:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:72:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::makeCone()':
../occQt/occQt.cpp:299:75: error: conversion from 'BRepPrimAPI_MakeCone' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoReducer = BRepPrimAPI_MakeCone(anAxis, 3.0, 1.5, 5.0);
                                                                           ^
../occQt/occQt.cpp:299:75: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp:305:72: error: conversion from 'BRepPrimAPI_MakeCone' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoCone = BRepPrimAPI_MakeCone(anAxis, 3.0, 0.0, 5.0);
                                                                        ^
../occQt/occQt.cpp:305:72: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::makeSphere()':
../occQt/occQt.cpp:319:66: error: conversion from 'BRepPrimAPI_MakeSphere' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoSphere = BRepPrimAPI_MakeSphere(anAxis, 3.0);
                                                                  ^
../occQt/occQt.cpp:319:66: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::makeCylinder()':
../occQt/occQt.cpp:332:75: error: conversion from 'BRepPrimAPI_MakeCylinder' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoCylinder = BRepPrimAPI_MakeCylinder(anAxis, 3.0, 5.0);
                                                                           ^
../occQt/occQt.cpp:332:75: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp:338:84: error: conversion from 'BRepPrimAPI_MakeCylinder' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoPie = BRepPrimAPI_MakeCylinder(anAxis, 3.0, 5.0, M_PI_2 \* 3.0);
                                                                                    ^
../occQt/occQt.cpp:338:84: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::makeTorus()':
../occQt/occQt.cpp:352:69: error: conversion from 'BRepPrimAPI_MakeTorus' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoTorus = BRepPrimAPI_MakeTorus(anAxis, 3.0, 1.0);
                                                                     ^
../occQt/occQt.cpp:352:69: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp:358:77: error: conversion from 'BRepPrimAPI_MakeTorus' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoElbow = BRepPrimAPI_MakeTorus(anAxis, 3.0, 1.0, M_PI_2);
                                                                             ^
../occQt/occQt.cpp:358:77: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::makeFillet()':
../occQt/occQt.cpp:372:70: error: conversion from 'BRepPrimAPI_MakeBox' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoBox = BRepPrimAPI_MakeBox(anAxis, 3.0, 4.0, 5.0);
                                                                      ^
../occQt/occQt.cpp:372:70: note: candidates are:
In file included from ../occQt/occQt.cpp:36:0:
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:76:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:72:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::makeChamfer()':
../occQt/occQt.cpp:392:70: error: conversion from 'BRepPrimAPI_MakeBox' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoBox = BRepPrimAPI_MakeBox(anAxis, 3.0, 4.0, 5.0);
                                                                      ^
../occQt/occQt.cpp:392:70: note: candidates are:
In file included from ../occQt/occQt.cpp:36:0:
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:76:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:72:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::testCut()':
../occQt/occQt.cpp:541:70: error: conversion from 'BRepPrimAPI_MakeBox' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoBox = BRepPrimAPI_MakeBox(anAxis, 3.0, 4.0, 5.0);
                                                                      ^
../occQt/occQt.cpp:541:70: note: candidates are:
In file included from ../occQt/occQt.cpp:36:0:
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:76:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:72:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp:542:66: error: conversion from 'BRepPrimAPI_MakeSphere' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoSphere = BRepPrimAPI_MakeSphere(anAxis, 2.5);
                                                                  ^
../occQt/occQt.cpp:542:66: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::testFuse()':
../occQt/occQt.cpp:574:70: error: conversion from 'BRepPrimAPI_MakeBox' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoBox = BRepPrimAPI_MakeBox(anAxis, 3.0, 4.0, 5.0);
                                                                      ^
../occQt/occQt.cpp:574:70: note: candidates are:
In file included from ../occQt/occQt.cpp:36:0:
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:76:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:72:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp:575:66: error: conversion from 'BRepPrimAPI_MakeSphere' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoSphere = BRepPrimAPI_MakeSphere(anAxis, 2.5);
                                                                  ^
../occQt/occQt.cpp:575:66: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp: In member function 'void occQt::testCommon()':
../occQt/occQt.cpp:600:70: error: conversion from 'BRepPrimAPI_MakeBox' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoBox = BRepPrimAPI_MakeBox(anAxis, 3.0, 4.0, 5.0);
                                                                      ^
../occQt/occQt.cpp:600:70: note: candidates are:
In file included from ../occQt/occQt.cpp:36:0:
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:76:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeBox.hxx:72:17: note: BRepPrimAPI_MakeBox::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
../occQt/occQt.cpp:601:66: error: conversion from 'BRepPrimAPI_MakeSphere' to 'TopoDS_Shape' is ambiguous
     TopoDS_Shape aTopoSphere = BRepPrimAPI_MakeSphere(anAxis, 2.5);
                                                                  ^
../occQt/occQt.cpp:601:66: note: candidates are:
In file included from /usr/include/oce/BRepPrimAPI_MakeCone.hxx:14:0,
                 from ../occQt/occQt.cpp:37:
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:47:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Solid()
 Standard_EXPORT operator TopoDS_Solid();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:43:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Shell()
 Standard_EXPORT operator TopoDS_Shell();
                 ^
/usr/include/oce/BRepPrimAPI_MakeOneAxis.hxx:39:17: note: BRepPrimAPI_MakeOneAxis::operator TopoDS_Face()
 Standard_EXPORT operator TopoDS_Face();
                 ^
In file included from /usr/include/oce/BRepBuilderAPI_MakeVertex.hxx:14:0,
                 from ../occQt/occQt.cpp:29:
/usr/include/oce/BRepBuilderAPI_MakeShape.hxx:44:17: note: BRepBuilderAPI_MakeShape::operator TopoDS_Shape() const
 Standard_EXPORT operator TopoDS_Shape() const;
                 ^
make: **\* [occQt.o] Error 1
18:05:36: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project occQt (kit: Desktop)
When executing step 'Make'
18:05:36: Elapsed time: 00:02.

**Comment by eryar** [comment]
Hi gregorito,

Thanks for your effort to compile occQt on ubuntu.

I only compiled the occQt and running occQt in Windows.

I will check the error info and compile it on Debian soon.

Best Regards,
Shing Liu

**Comment by KASUYASU** [comment]
Hi all,
The error
  /usr/include/oce/math_Vector.hxx:273:31: error: expected unqualified-id before numeric constant
is caused from the reason that the header file 'x.h' has a define 'Opposite'. 

The error
  ../occQt/occQt.cpp:299:75: error: conversion from 'BRepPrimAPI_MakeCone' to 'TopoDS_Shape' is ambiguous
may be  solved if you rewrite 
  TopoDS_Shape aTopoBox = BRepPrimAPI_MakeBox(3.0, 4.0, 5.0).Shape();
etc.
Kazu

**Comment by eryar** [comment]
Hi KASUYASU,

Thanks for your suggestion.

Best Regards,
Shing Liu

**Comment by eryar** [comment]
Compile the occQt on ubuntu have been fixed by @shrdluk .
Thanks.

**Comment by aarti2598** [comment]
Hey, Mr. @eryar Can you please provide whole procedure to compile occQt in ubuntu 18.04 with qmake. I tried it in the way I knew but I'm getting number of errors, so I think the process is wrong.
