### ISSUE TITLE
Error compiling the code

### ISSUE THREAD

**Issue by aarti2598** [eryar/occQt#22]
Hello, 
I'm trying to compile the occQt code in Ubuntu 18.04 on command prompt. I modified the project file (occQt.pro). I Included paths to header files and changed the CASROOT. Also I changed the order of header files to get rid of the "error qmetatype.h..."
But I'm still getting the below errors. It says undefined reference to some functions.
Can anyone please help !

![Screenshot from 2020-12-05 11-17-32](https://user-images.githubusercontent.com/75235824/101235258-186edd80-36ed-11eb-885e-d4c1eefcb559.png)

**Comment by eryar** [comment]
Hello, these errors are the occ lib link error, your occ lib path is wrong.
