### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by tyc1998** [eryar/occQt#25]
According to what you said, I modified occQt.pro and then used the qt plugin in vs to build, but many link errors occurred. Below is my screenshot:
![image](https://user-images.githubusercontent.com/31647878/110474912-31879000-811b-11eb-8650-3d4f83fca1c7.png)

I don't know where the problem is, I look forward to your advice.
By the way, I downloaded opencascade directly from the occt official website, and then did not compile it, and used its own lib.

**Comment by eryar** [comment]
1 Config the correct lib path for opencascade;
2 Config the Win32/64 same with your opencascade;
