### ISSUE TITLE
Compilation on ubuntu

### ISSUE THREAD

**Issue by ghost** [eryar/occQt#3]
Hi I was trying to compile the project with all the instructions for linux (ubuntu 14.04) README.TXT I have the following error:

/usr/include/oce/math_Vector.hxx:277: Error: expression can not be used as a front return function (); ^

Any idea how to make it work? thank you very much!

**Comment by eryar** [comment]
Hi Nesty92,
I also tried to compile occQt on Debian and have the same errors, refer to:
http://www.cppblog.com/eryar/archive/2015/05/21/210710.html

So the error is not from the class math_Vector.

**Comment by ghost** [comment]
Hi eryar,
Thanks for answering 
The problem is with the libs "X11.h" and the libs OCE
You can try to add:
#undef Opposite 
between qt libs and oce libs in your example not yet trying bat in other viewer of this is a solutions in next days i well try this in your example. regards

**Comment by eryar** [comment]
Hi Nesty92,

I try to include the 

``` c
#include <X11/Xlib.h>
```

 before 

``` c
#include <math_Vector.hxx>
```

and the errors appears, and I found the conflict from the define in X.h:

``` c
/* Window stacking method (in configureWindow) */

#define Above                   0
#define Below                   1
#define TopIf                   2
#define BottomIf                3
#define Opposite                4
```

I will try to find the solutions for this.

Best Regards,
Shing Liu

**Comment by eryar** [comment]
Compile the occQt on ubuntu have been fixed by @shrdluk 
Thanks.
