### ISSUE TITLE
OpenCASCADE 7.0 support

### ISSUE THREAD

**Issue by starseeker** [eryar/occQt#6]
Would it be possible to update this example to work with the upcoming OpenCASCADE 7.0 release?

http://dev.opencascade.org/index.php?q=node/1140

**Comment by eryar** [comment]
Hi,
I will update it for the OpenCASCADE7.0.
Now I am trying to compile it with the OpenCASCADE7.0 beta version.

**Comment by eryar** [comment]
@starseeker 
I have try to compile occQt with OpenCASCADE7.0.0, to port to OpenCASCADE7.0.0 do not need
to modify any code of occQt, it will compile ok!
