### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by lanigb** [eryar/occQt#7]
Hi,

I am trying to compile occQT on ubuntu trusty.
First I got the following error : 
g++ -c -m64 -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/include/oce -I/usr/X11R6/include -I. -I. -o occView.o occView.cpp
occView.cpp:21:25: fatal error: Graphic3d.hxx: Aucun fichier ou dossier de ce type
 #include <Graphic3d.hxx>
 (Aucun fichier ou dossier de ce type = no such file or folder)

I modified occView.cpp 
# include <Graphic3d.hxx> to
# include <InterfaceGraphic_Graphic3d.hxx>

but now I got a new error.
occView.cpp: In constructor ‘OccView::OccView(QWidget_)’:
occView.cpp:66:30: error: ‘Graphic3d’ has not been declared
         GetGraphicDriver() = Graphic3d::InitGraphicDriver(aDisplayConnection);
                              ^
make: *_\* [occView.o] Erreur 1
I have 
liboce-visualization-dev:amd64                 0.17-1ppa1~ubuntu14.04.2                            amd64        OpenCASCADE Community Edition CAE platform library development files
ii  liboce-visualization10:amd64                   0.17-1ppa1~ubuntu14.04.2                            amd64        OpenCASCADE Community Edition CAE platform shared library
installed on my computer.
Are they too old ?

Thanks for your help

**Comment by eryar** [comment]
Hi lanigb,

Maybe you should use the lastest version Qt and oce.

Best Regards,
Shing Liu

**Comment by ptzptz** [comment]
Hi eryar,

I can't find the Graphic3d.hxx file in OpenCASCADE 6.9.0, 6.8.0, or 6.7.1 (I didn't check earlier releases). However it is in liboce-visualization-dev.

How can I include this properly?

Thank you.

**Comment by eryar** [comment]
Hi ptzptz,

you can remove the Graphic3d.hxx and use the following code to create the graphic driver directly:
    // Get graphic driver if it exists, otherwise initialise it
    if (GetGraphicDriver().IsNull())
    {
        GetGraphicDriver() = new OpenGl_GraphicDriver(aDisplayConnection);
    }

Best Regards
Shing Liu

**Comment by eryar** [comment]
Hi @ptzptz ,

you can remove the Graphic3d.hxx and include OpenGl_GraphicDriver.hxx instead and use the following code to create the graphic driver directly:

``` c
// Get graphic driver if it exists, otherwise initialise it
 if (GetGraphicDriver().IsNull())
{
    GetGraphicDriver() = new OpenGl_GraphicDriver(aDisplayConnection);
}
```

Best Regards
Shing Liu

**Comment by lanigb** [comment]
Thanks for the tips, but unfortunately, it still doesn't compile.
   ^
/usr/include/oce/OpenGl_GlFunctions.hxx:749:3: error: ‘PFNGLMULTTRANSPOSEMATRIXFPROC’ does not name a type
   PFNGLMULTTRANSPOSEMATRIXFPROC     glMultTransposeMatrixf;
   ^
/usr/include/oce/OpenGl_GlFunctions.hxx:750:3: error: ‘PFNGLMULTTRANSPOSEMATRIXDPROC’ does not name a type
   PFNGLMULTTRANSPOSEMATRIXDPROC     glMultTransposeMatrixd;

Thanks for you help

**Comment by eryar** [comment]
@lanigb 

You can check this for reference:
http://www.cnblogs.com/opencascade/p/4192688.html#3155267
Maybe the header file include sequence cause the problem,
Try this to include the 

``` C
#include <OpenGl_GraphicDriver.hxx> 
```

before:

``` C
#include <QtOpenGL\QGLWidget>
```

in the occView.h file.

Regards,
Shing Liu

**Comment by lanigb** [comment]
Thansks.

It solves the problem with the FNGLMULTTRANSPOSEMATRIXDPROC’ does not name a type stuff.

I have still compile errors like this

/usr/include/oce/math_Vector.hxx: In member function ‘math_Vector math_Vector::operator-()’:
/usr/include/oce/math_Vector.hxx:277:21: error: expression cannot be used as a function
     return Opposite();

**Comment by eryar** [comment]
@lanigb ,

Sorry,
I do not have Ubuntu OS currently, you can try to solve the problem yourself first.
I am using Visual Studio&Qt Plugin&OCC to compile the occQt.

Or you can try to compile the occQt with OCC directly other than OCE.

**Comment by lanigb** [comment]
OK, thanks. I didn't grasped that OCC and OCE where in fact different enough as to prevent building.

**Comment by ghost** [comment]
First of all, thanks for this project. It has been very helpful.
I was having the same problems trying to compile on Linux with OCC 7.0.0. I created a fork of this project and posted all the changes I made to compile on both Windows and Linux, using OCC 6.9.0 on Windows and OCC 7.0.0 on Linux. The changes are in branch `occ-7.0.0`. Here is the link to the fork:
https://github.com/hpmachining/occQt

Thank You,
Paul

**Comment by eryar** [comment]
@hpmachining 
Great!

**Comment by eryar** [comment]
Thanks to @hpmachining ,

I think this issue could be closed.
