### ISSUE TITLE
Refresh    bug!

### ISSUE THREAD

**Issue by hustliuyang** [eryar/occQt#8]
我的运行occQt的时候遇到一些问题！场景的显示会出现空白，仿佛刷新不及时。

https://yunpan.cn/cSBa2YNFUaPsg  访问密码 b8b4  
这是我调试运行时的截图，困扰了好几天也不知道如何解决。请指教！

不翻译成英语啦，万一给读者造成误导就不好啦。

**Comment by hustliuyang** [comment]
[http://user.qzone.qq.com/2561589421/photo/V10vALpP0PPiur/batchid/1464098731390000](url)

**Comment by eryar** [comment]
hust 难道是华科的？

这个问题我看看。

**Comment by hustliuyang** [comment]
hehe  朋友是华科的吗？ 我是刚接触OpenCASCADE，磕磕绊绊的遇到不少问题。以前弄OSG的时候，是通过刷新Frame()完成显示的，但是OpenCASCADE这个不知道为什么会出现空白现象。

**Comment by eryar** [comment]
The source code is updated, you can download the lastest version to have a try.

**Comment by hustliuyang** [comment]
Nice Work!!!   

Both environment variables CSF_ShadersDirectory and CASROOT are undefined!

 qputenv("CASROOT", "C:/OpenCASCADE6.9.0/opencascade-6.9.0");   // OK

**Comment by eryar** [comment]
I have add the environment variable CSF_ShadersDirectory by
OSD_Environment 

You can try it.
